config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users
  root to: "pages#home"
  get "/about", to: "pages#about", as: "about"
  get "/transactionslist", to: "transactions#transactionslist", as: "transactionslist"
  get "/success", to: "transactions#success", as: "transaction_success"
  post "/transactions/webhook", to: "transactions#webhook", as: "webhook"
  # post "/transactions", to: "transactions#create_transaction_intent", as: "create_transaction"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :transactions
  has_one_attached :product_image

  before_save :remove_whitespace
  before_save :replace_ebay
  before_save :convert_price_to_cents, if: :product_price_changed?


  private
  def remove_whitespace
    self.product_name = self.product_name.strip
    self.product_description = self.product_description.strip
  end

  def replace_ebay
    self.product_name = self.product_name.gsub(/ebay/i, "marketplace")
    self.product_description = self.product_description.gsub(/ebay/i, "marketplace")
  end

  def convert_price_to_cents
    self.product_price = (self.attributes_before_type_cast["product_price"].to_f * 100).round
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_one :address, dependent: :destroy
  has_many :transactions
  has_many :purchased_products, through: :transactions, source: :product

  accepts_nested_attributes_for :address, allow_destroy: true
  before_save :remove_whitespace
  before_save :enforce_lower_case_username

  def with_address
    build_address if address.nil?
    self
  end

  private
  def remove_whitespace
    self.fullname = self.fullname.strip
    self.profile_info = self.profile_info.strip
  end

  def enforce_lower_case_username
    self.username = self.username.downcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_sanitized_params, if: :devise_controller?
  before_action :set_sample_products

  protected
  def configure_sanitized_params
      devise_parameter_sanitizer.permit(:sign_up) do |u|
          u.permit(:fullname, :username, :email, :profile_info, :password, :password_confirmation, address_attributes: [:address_street, :address_state, :address_country, :address_postcode])
      end

      devise_parameter_sanitizer.permit(:account_update) do |u|
          u.permit(:fullname, :username, :email, :profile_info, :password, :password_confirmation, :current_password, address_attributes: [:address_street, :address_state, :address_country, :address_postcode])
      end
  end

  private
    def set_sample_products
        @sample_products = Product.all.sample(4)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    # check that a user is logged in before taking you to the home page
    before_action :authenticate_user!, except: [:home, :about]

    def home
    end

    def about
    end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorise_user, only: [:edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit]


  # GET /products page that lists all products
  # explicitly renders the products index.html.erb file in products views folder
  def index
    @products = Product.all
    # we will loop through every product and its attributes in index.html.erb 
  end

  # GET /products/1 renders show.html.erb that shows individual products
  # creating payment intent, showing our Stripe gem payment option when we render the page for each product
  def show
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      customer_email: current_user&.email,
      line_items: [{
        name: @product.product_name,
        description: @product.product_description,
        amount: @product.product_price,
        currency: 'aud',
        quantity: 1
      }],
      payment_intent_data: {
        metadata: {
          user_id: current_user&.id,
          product_id: @product.id
        }
      },
      success_url: "#{root_url}/success?title=#{@product.product_name}",
      cancel_url: "#{root_url}/products"
    )
    
    @session_id = session.id
    puts "*******"
    pp @session_id
    puts "*******"
  end

  # GET /products/new page that allows creation of individual product
  # explicitly renders the products new.html.erb file in products views folder
  def new
    @product = Product.new
  end

  # GET /products/1/edit page that allows edit of an individual product
  # explicitly renders the products edit.html.erb file in products views folder
  def edit
  end

  # POST /products does not render a page
  def create
    @product = current_user.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 edits and does not render a page
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 does not render a page
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only our trusted attribute parameters are passed through. 
    def product_params
      params.require(:product).permit(:user_id, :category_id, :product_name, :product_description, :product_price, :product_stock, :product_image)
    end

    def set_categories
      @categories = Category.all
      # this find params doesn't work, gets can't find params id
      # @categories = Category.find(params[:id])
    end

    def authorise_user
      if current_user.id != @product.user.id
        flash[:error] = "Sorry - You can't do that."
        redirect_to product_path
      end
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:webhook]
  def success
      @title = params[:product_name]
  end

  def webhook
    transaction_id = params[:data][:object][:payment_intent]
    transaction = Stripe::PaymentIntent.retrieve(transaction_id)
    pp transaction

    product_id = transaction.metadata.product_id
    user_id = transaction.metadata.user_id
    
    @product = Product.find(product_id)
    @product.update(product_stock: false)
    
    @seller = User.find(@product.user_id)
    @buyer = User.find(user_id)

    @transaction = Transaction.create(product_id: product_id, user_id: user_id)
    TransactionsMailer.with(seller: @seller, product: @product, buyer: @buyer).new_transaction_email.deliver_later
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
    def image_select(product)
        return product.product_image if product.product_image.attached?
        # if no product image attached the default placeholder image will be used.
        return "placeholder.jpg"
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lcm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&display=swap" rel="stylesheet">
    <script src="https://js.stripe.com/v3"></script>
  </head>

  <body>
    
    <%= render "/shared/navbar" %>

    <% flash.each do |key,value| %> 
      <div class="alert alert-warning alert-dismissable fade show" role="alert">
        <%= value %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true"> &times; </span>
        </button>
      </div>
    <% end %>
    
    <%= yield %>
    <%= render "/shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<br />
<h2>About</h2>
<main id="about">
  <section>
    <%= image_tag "aboutimage.jpg", alt:"A woman with her hair up, in a yellow jumper painting pink flowers.", :class=>"image" %>
  </section>
  <section class="abouttext">
    <p>
      <strong>Lockdown Creatives</strong> is a Marketplace that aims to support artists, creatives and performers in lockdown by offering <strong>a new revenue stream.</strong>
    </p>
    <p>
      The platform provides opportunity for creatives to build upon their skills to produce kits or experiences that <strong>push the boundaries</strong> of their creativity. 
    </p>
    <p>
      We're all looking for new ways to <strong>stay entertained,</strong> maintain creativity and <strong>feel good</strong> during lockdown. 
      Lockdown Creatives offers new ways for customers to stay informed about their favourite creatives, participating in fueling their income whilst the government haults the entertainment and arts industries.
    </p>
    <p>
      Customers grow their interaction with your business online and at home.
    </p>
    <p>
      We understand you can't be out in the wild flaunting your skills during lockdown, but you can still <strong>connect with your audience.</strong> 
    </p>
    <p>
      Delivery and schedules are maintained outside the app by you the creative to ensure you're producing only at the capacity you wish. This means if the pandemic is getting you down you can take that mental health break. It's your time, no one elses, so <strong>work within your means.</strong> 
    </p>
    <p>
      <strong>Create that side hustle!</strong> Grow this additional revenue stream outside of pandemic times.
    </p>
    <br />
    <div class="landing-buttons">
      <button>
        <%= link_to "SIGN UP", new_user_registration_path %>
      </button>
      <button>
        <%= link_to "LOG IN", new_user_session_path %>
      </button>
      <button>
        <%= link_to "SHOP NOW", products_path %>
      </button>
    </div>
  </section>
</main>

app/views/pages/home.html.erb
<br/>
<h2>Create that side hustle!</h2>
<main id="home">
  <section>
    <%= image_tag "heroimage.jpg", alt:"flowers, markers and creative note book full of art.", :class=>"image" %>
  </section>
  <article>
    <h2>A marketplace for lockdown experiences.<br/>
    By artists, for lovers of art.
    </h2>
    <h5>
      Lockdown Creatives is a Marketplace that aims to support artists, creatives and performers in lockdown by offering a new revenue stream.
    </h5>
    <div class="landing-buttons">
    <% if !user_signed_in? %>
      <button>
        <%= link_to "SIGN UP", new_user_registration_path %>
      </button>
    <% end %>
    <button>
      <%= link_to "SHOP NOW", products_path %>
    </button>
    </div>
  </article>
</main>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div>
    <%= f.association :category, collection: @categories.map {|c| [c.category_name, c.id]} %>
    <%= f.input :product_name %>
    <%= f.input :product_description %>
    <%= f.input :product_price, step: "0.01" %>
    <%= f.input :product_stock, as: :radio_buttons, label: "Product in stock?" %>
    <%= f.file_field :product_image, class:"smallproductimage" %>
  </div><br />


  <div>
    <%= f.button :submit, :class=>'specialbtn' %>
  </div><br />
<% end %>

app/views/products/edit.html.erb
<br />
<h2>Edit <%= @product.product_name %></h2>
<main>
  <%= render 'form', product: @product %>

  <h6>
    <%= link_to "See #{@product.product_name}", @product %><br />
    <%= link_to 'Back to ALL Products', products_path %>
  </h6>
</main>

app/views/products/index.html.erb
<%= notice %>
<br />
<h2>All Products</h2>

<main id="productsindex">
  <section class="imageholder">
    <% @products.each do |product| %>
      <div class='productlisting'>
        <div class="productimagecontainer">
          <p class="categoryname"><%= product.category.category_name %></p>
          <%= image_tag image_select(product), class:"smallproductimage" %>
        </div>
        <div class="productcardbody">
          <span class="productname"><%= link_to "#{product.product_name}", product %></span><br />
          $ <%= product.product_price / 100 %>
          
          <br />

          <span>
            <% if user_signed_in? && current_user.id == product.user_id %>
              <%= link_to 'Show', product %> | 
              <%= link_to 'Edit', edit_product_path(product) %> | 
              <%= link_to 'Delete Product', product, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </span>
        </div>
      </div>
    <% end %>
  </section>

  <br /><br /><br />

  <% if user_signed_in? %>
    <%= link_to 'Create a New Product', new_product_path %>
  <% end %>
</main>

app/views/products/new.html.erb
<br/>
<h2>New Product</h2>
<main>
    <%= render 'form', product: @product %>

    <%= link_to 'Back', products_path %>
</main>

app/views/products/show.html.erb
<br />
<h2><%= @product.product_name %></h2>
<main id="show">
  <section>
    <%= image_tag image_select(@product), class:"productimage" %>
  </section>
  <section class="productinfo">
    <h4>
      <strong><%= @product.product_name %></strong> | <%= @product.category.category_name %><br /><br />
    </h4>
    <p>
      <%= @product.product_description %><br /><br />
      <% if @product.product_stock == true %>
        Available
        <% else %>
        Unavailable
      <% end %><br />
      <strong>$ <%= @product.product_price / 100 %></strong>
    </p>
    <br />
    <% if current_user && @product.product_stock == false %>
      <button class="specialbtn" disabled>
        SOLD
      </button>
      <%= link_to "Contact Seller", root_path %>
    <% elsif current_user && @product.product_stock == true %>
      <button data-stripe="payment" class="specialbtn">
        Buy Now: $<%= @product.product_price / 100.0 %>
      </button>
    <% else %>
      <%= button_to "Login to buy", new_user_session_path, class:"specialbtn" %>
    <% end %>
    <br />
    <br />
    <br />
    <h6 class="productnav">
      <% if user_signed_in? && current_user.id == @product.user_id %>
        <%= link_to "Edit #{@product.product_name}", edit_product_path(@product), :class=>'back' %>
      <% end %>
      <br />

      <br />
      <%= link_to 'Back to ALL Products', products_path, :class=>'back'  %>
    </h6>
  </section>
</main>



<script>
  document.querySelector("[data-stripe='payment']")
    .addEventListener("click",()=>{
      const stripe = Stripe(
        "<%=Rails.application.credentials.dig(:stripe, :public_key)%>"
      );
      stripe.redirectToCheckout({
        sessionId: "<%= @session_id%>"
      });
    })
</script>

app/views/shared/_footer.html.erb
<nav class="footernavs">
  <section>
    <div class="footerproductimages">
      <% @sample_products.each do |product| %>
        <%= link_to product do %>
          <%= image_tag image_select(product), class:"footerproductimg" %>
        <% end %>
      <% end %>
    </div>
  </section>
  <ul>
    <li><a href="https://github.com/leberSmeaton/lcm">Repo</a></li>
    <li><a href="www.linkedin.com/in/bella-leber-smeaton">LinkedIn</a></li>
    <li><a href="www.facebook.com">Facebook</a></li>
    <li><a href="www.instagram.com">Instagram</a></li>
    <li><a href="www.twitter.com">Twitter</a></li>
  </ul>
</nav>

app/views/shared/_navbar.html.erb
<nav class="headernavs">
  <h1><%= link_to "Lockdown Creatives", root_path %></h1>
  <ul>
    <li><%= link_to "Products", products_path %></li>
    <li><%= link_to "About", about_path %></li>
    
    <% if user_signed_in? %>
      <li>
        <%= link_to "Sell", new_product_path %>
      </li>
      <li>
        <%= link_to "Profile", edit_user_registration_path %>
      </li>
      <li>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "Sign Up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "Log In", new_user_session_path %>
      </li>
    <% end %>
    
  </ul>
</nav>

app/views/transactions/success.html.erb
<br/>
<h2>Thanks for your purchase!</h2>
<main id="success">
  <section>
    <%= image_tag "heroimage.jpg", alt:"flowers, markers and creative note book full of art.", :class=>"image" %>
  </section>
  <article class="abouttext">
    <h4>The - <strong><%= @title %>******</strong> - is now yours!</h4>
    <p>Lorem ipsum dolor sit amet.</p>
    <div>
      <%= image_tag "tick-icon.png", class:"successtick" %>
    </div>
    <br />
    <br />
    <br />
    <%= link_to "Previous Transactions", transactionslist_path, :class=>'back' %>  
  </article>
</main>

app/views/transactions/transactionslist.html.erb
<br/>
<h2>Create that side hustle!</h2>
<main id="transactionlist">
  <h2><%= current_user.fullname %>'s Transaction History</h2>

  <article class="transactionlistcontainer">
    <% current_user.purchased_products.each do |product| %>
      <div class="transactionitem">
        <div>
          <%= image_tag product.product_image, class:"transactionimg" if product.product_image? %>
        </div>
        <ul>
          <li><strong>Product Purchased: <%= product.product_name %></strong></li><br />
          <li>Date Purchased: <%= product.created_at %></li>
          <li>Product Info: <%= product.product_description %></li>
          <li>Total Cost: $<%= product.product_price / 100 %></li><br />
          <li>To arrange online delivery please contact artist directly, </li>
          <li>Artist Info: <%= product.user.fullname %> | <%= product.user.email %></li>
        </ul>
      </div>
    <% end %>
  </article>
</main>